let users = [
	{
		name: 'Thai Hoang Nguyen',
		email: 'thaihoang.nguyen@acomsolutions.com',
		password: 'rivaldo',
		id: 'thaihoang.nguyen@acomsolutions.com',
		categories: ['category_bank_account'],
		testsuites: [],
		type: 'user'
	},
	{
		name: 'Thien Vo',
		email: 'thien.vo@acomsolutions.com',
		password: 'rivaldo',
		type: 'user',
		id: 'thien.vo@acomsolutions.com',
		testsuites: [],
		categories: ['category_payment']
	},
]

let categories = [
	{
		name: 'Bank Account',
		description: 'Bank Account Category',
		author: 'thaihoang.nguyen@acomsolutions.com',
		id: 'category_bank_account',
		type: 'category',
		testsuites: ['testsuite_pending', 'testsuite_approval'],
		status: 'pass',
		work_items: [15149, 15150]
	},
	{
		name: 'Payment',
		description: 'Payment Category',
		author: 'thien.vo@acomsolutions.com',
		id: 'category_payment',
		type: 'category',
		testsuites: ['testsuite_notification', 'testsuite_ach'],
		status: 'fail',
		work_items: [15151]
	}
]

let testsuites = [
	{
		name: 'Pending',
		description: 'testsuite Pending',
		author: 'thaihoang.nguyen@acomsolutions.com',
		id: 'testsuite_pending',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_pending', 'testgroup_primary_pending'],
		testcases: ['testcase_pending_1', 'testcase_pending_2'],
		category: 'category_payment', //không quan trọng phải có item này
		work_items: [15152, 15153]
	},
	{
		name: 'Approval',
		description: 'testsuite Aproval',
		author: 'thien.vo@acomsolutions.com',
		id: 'testsuite_approval',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_approval', 'testgroup_primary_approval'],
		testcases: ['testcase_approval_1', 'testcase_approval_2'],
		category: 'category_payment',
		work_items: [15154, 15155]
	},
	{
		name: 'Notification',
		description: 'testsuite Notification',
		author: 'thaihoang.nguyen@acomsolutions.com',
		id: 'testsuite_notification',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_notification', 'testgroup_primary_notification'],
		testcases: [],
		category: 'category_bank_account',
		work_items: [15156, 15157]
	},
	{
		name: 'ACH',
		description: 'testsuite ACH',
		author: 'thien.vo@acomsolutions.com',
		id: 'testsuite_ach',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_ach', 'testgroup_primary_ach'],
		testcases: [],
		category: 'category_bank_account',
		work_items: [15158, 15159]

	}
]

let testgroups = [
	{
		name: 'Group Preconfig Pending',
		description: 'testgroup Preconfig Pending',
		id: 'testgroup_preconfig_pending',
		testcases: ['testcase_preconfig_pending_1', 'testcase_preconfig_pending_2'],
		testsuite: 'testsuite_pending',
		work_items: [15160, 15161]
	},
	{
		id: 'testgroup_primary_pending',
		name: 'Group Primary Pending',
		description: 'testgroup Primary Pending',
		testcases: ['testcase_primary_pending_1', 'testcase_primary_pending_2'],
		testsuite: 'testsuite_pending',
		work_items: [15162, 15163]
	},
	{
		id: 'testgroup_preconfig_approval',
		name: 'Group Preconfig Approval',
		description: 'testgroup Preconfig Aproval',
		testcases: ['testcase_preconfig_approval_1', 'testcase_preconfig_approval_2'],
		testsuite: 'testsuite_approval',
		work_items: [15164, 15165]
	},
	{
		id: 'testgroup_primary_approval',
		name: 'Group Primary Approval',
		description: 'testgroup Primary Aproval',
		testcases: ['testcase_primary_approval_1', 'testcase_primary_approval_2'],
		testsuite: 'testsuite_approval',
		work_items: [15166, 15167]
	},
	{
		id: 'testgroup_preconfig_notification',
		name: 'Group Preconfig Notification',
		description: 'testgroup Preconfig Notification',
		testcases: ['testcase_preconfig_notification_1'],
		testsuite: 'testsuite_notification',
		work_items: [15168, 15169]
	},
	{
		id: 'testgroup_primary_notification',
		name: 'Group Primary Notification',
		description: 'testgroup Primary Notification',
		testcases: ['testcase_primary_notification_1'],
		testsuite: 'testsuite_notification',
		work_items: [15170, 15171]
	},
	{
		id: 'testgroup_preconfig_ach',
		name: 'Group Preconfig ACH',
		description: 'testgroup Preconfig ACH',
		testcases: ['testcase_preconfig_ach_1'],
		testsuite: 'testsuite_ach',
		work_items: [15172, 15173]
	},
	{
		id: 'testgroup_primary_ach',
		name: 'Group Primary ACH',
		description: 'testgroup Primary ACH',
		testcases: ['testcase_primary_ach_1'],
		testsuite: 'testsuite_ach',
		work_items: [15174, 15175]
	}
]

let testcases = [
	{
		id: 'testcase_pending_1',
		name: 'Testcase Pending 1',
		description: 'testcase Pending 1',
		type: 'testcase',
		keywords: ['keyword_1','keyword_2','keyword_3','keyword_4','keyword_5',],
		testsuite: 'testsuite_pending',
		work_items: [15176],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_pending_2',
		name: 'Testcase Pending 2',
		description: 'testcase Pending 2',
		type: 'testcase',
		keywords: ['keyword_6','keyword_7','keyword_8','keyword_9','keyword_10',],
		testsuite: 'testsuite_pending',
		work_items: [15177],
		enabled: true,
		primary: false,
		dependency: 'testcase_pending_1',
	},
	{
		id: 'testcase_approval_1',
		name: 'Testcase Aproval 1',
		description: 'testcase Aproval 1',
		type: 'testcase',
		keywords: ['keyword_11','keyword_12','keyword_13','keyword_14','keyword_15',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15178],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_approval_2',
		name: 'Testcase Aproval 2',
		description: 'testcase Aproval 2',
		type: 'testcase',
		keywords: ['keyword_16','keyword_17','keyword_18','keyword_19','keyword_20',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15179],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_pending_1',
		name: 'Testcase Preconfig Pending 1',
		description: 'testcase Preconfig Pending 1',
		type: 'testcase',
		keywords: ['keyword_21','keyword_22','keyword_23','keyword_24','keyword_25',],
		testgroup: 'testgroup_preconfig_pending',
		testsuite: '',
		work_items: [15180],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_pending_2',
		name: 'Testcase Preconfig Pending 2',
		description: 'testcase Preconfig Pending 2',
		type: 'testcase',
		keywords: ['keyword_26','keyword_27','keyword_28','keyword_29','keyword_30',],
		testgroup: 'testgroup_preconfig_pending',
		testsuite: '',
		work_items: [15181],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_pending_1',
		name: 'Testcase Primary Pending1',
		description: 'testcase Primary Pending 1',
		type: 'testcase',
		keywords: ['keyword_31','keyword_32','keyword_33','keyword_34','keyword_35',],
		testgroup: 'testgroup_primary_pending',
		testsuite: '',
		work_items: [15182],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_primary_pending_2',
		name: 'Testcase Primary Pending2',
		description: 'testcase Primary Pending 2',
		type: 'testcase',
		keywords: ['keyword_36','keyword_37','keyword_38','keyword_39','keyword_40',],
		testgroup: 'testgroup_primary_pending',
		testsuite: '',
		work_items: [15183],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_approval_1',
		name: 'Testcase Preconfig Approval 1',
		description: 'testcase Preconfig Aproval 1',
		type: 'testcase',
		keywords: ['keyword_41','keyword_42','keyword_43','keyword_44','keyword_45',],
		testgroup: 'testgroup_preconfig_approval',
		testsuite: '',
		work_items: [15184],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_approval_2',
		name: 'Testcase Preconfig Approval 2',
		description: 'testcase Preconfig Aproval 2',
		type: 'testcase',
		keywords: ['keyword_46','keyword_47','keyword_48','keyword_49','keyword_50',],
		testgroup: 'testgroup_preconfig_approval',
		testsuite: '',
		work_items: [15185],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_approval_1',
		name: 'Testcase Primary Approval 1',
		description: 'testcase Primary Aproval 1',
		type: 'testcase',
		keywords: ['keyword_51','keyword_52','keyword_53','keyword_54','keyword_55',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15186],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_approval_2',
		name: 'Testcase Primary Approval 2',
		description: 'testcase Primary Aproval 2',
		type: 'testcase',
		keywords: ['keyword_56','keyword_57','keyword_58','keyword_59','keyword_60',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15187],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_notification_1',
		name: 'Testcase Preconfig Notification 1',
		description: 'testcase Preconfig Notification ',
		type: 'testcase',
		keywords: ['keyword_61','keyword_62','keyword_63','keyword_64','keyword_65',],
		testgroup: 'testgroup_preconfig_notification',
		testsuite: '',
		work_items: [15188],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_notification_1',
		name: 'Testcase Primary Notification 1',
		description: 'testcase Primary Notification 1',
		type: 'testcase',
		keywords: ['keyword_66','keyword_67','keyword_68','keyword_69','keyword_70',],
		testgroup: 'testgroup_preconfig_notification',
		testsuite: '',
		work_items: [15189],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_ach_1',
		name: 'Testcase Preconfig ACH1',
		description: 'testcase Preconfig ACH1',
		type: 'testcase',
		keywords: ['keyword_71','keyword_72','keyword_73','keyword_74','keyword_75',],
		testgroup: 'testgroup_preconfig_ach',
		testsuite: '',
		work_items: [15190],
		tickable: false,
		enabled: false,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_ach_1',
		name: 'Testcase Primary ACH 1',
		description: 'testcase Primary ACH ',
		type: 'testcase',
		keywords: ['keyword_76','keyword_77','keyword_78','keyword_79','keyword_80',],
		testgroup: 'testgroup_primary_ach',
		testsuite: '',
		work_items: [15191],
		enabled: true,
		primary: true,
		dependency: '',
	}
]

let steps = [
	{
		id: 'step_1',
		name: 'Step 1 Name',
		description: 'Step 1 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_1','param_2'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_2',
		name: 'Step 2 Name',
		description: 'Step 2 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_3','param_4'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_3',
		name: 'Step 3 Name',
		description: 'Step 3 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_5','param_6'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_4',
		name: 'Step 4 Name',
		description: 'Step 4 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_7','param_8'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},{
		id: 'step_5',
		name: 'Step 5 Name',
		description: 'Step 5 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_9','param_10'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_6',
		name: 'Step 6 Name',
		description: 'Step 6 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_11','param_12'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_7',
		name: 'Step 7 Name',
		description: 'Step 7 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_13','param_14'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_8',
		name: 'Step 8 Name',
		description: 'Step 8 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_15','param_16'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_9',
		name: 'Step 9 Name',
		description: 'Step 9 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_17','param_18'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_10',
		name: 'Step 10 Name',
		description: 'Step 10 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_19','param_20'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_11',
		name: 'Step 11 Name',
		description: 'Step 11 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_21','param_22'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_12',
		name: 'Step 12 Name',
		description: 'Step 12 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_23','param_24'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_13',
		name: 'Step 13 Name',
		description: 'Step 13 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_25','param_26'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_14',
		name: 'Step 14 Name',
		description: 'Step 14 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_27','param_28'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_15',
		name: 'Step 15 Name',
		description: 'Step 15 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_29','param_30'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_16',
		name: 'Step 16 Name',
		description: 'Step 16 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_31','param_32'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_17',
		name: 'Step 17 Name',
		description: 'Step 17 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_33','param_34'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_18',
		name: 'Step 18 Name',
		description: 'Step 18 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_35','param_36'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_19',
		name: 'Step 19 Name',
		description: 'Step 19 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_37','param_38'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_20',
		name: 'Step 20 Name',
		description: 'Step 20 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_39','param_40'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_21',
		name: 'Step 21 Name',
		description: 'Step 21 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_41','param_42'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_22',
		name: 'Step 22 Name',
		description: 'Step 22 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_43','param_44'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_23',
		name: 'Step 23 Name',
		description: 'Step 23 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_45','param_46'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_24',
		name: 'Step 24 Name',
		description: 'Step 24 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_47','param_48'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_25',
		name: 'Step 25 Name',
		description: 'Step 25 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_49','param_50'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_26',
		name: 'Step 26 Name',
		description: 'Step 26 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_51','param_52'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_27',
		name: 'Step 27 Name',
		description: 'Step 27 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_53','param_54'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_28',
		name: 'Step 28 Name',
		description: 'Step 28 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_55','param_56'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_29',
		name: 'Step 29 Name',
		description: 'Step 29 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_57','param_58'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_30',
		name: 'Step 30 Name',
		description: 'Step 30 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_59','param_60'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_31',
		name: 'Step 31 Name',
		description: 'Step 31 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_61','param_62'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_32',
		name: 'Step 32 Name',
		description: 'Step 32 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_63','param_64'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_33',
		name: 'Step 33 Name',
		description: 'Step 33 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_65','param_66'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_34',
		name: 'Step 34 Name',
		description: 'Step 34 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_67','param_68'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_35',
		name: 'Step 35 Name',
		description: 'Step 35 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_69','param_70'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_36',
		name: 'Step 36 Name',
		description: 'Step 36 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_71','param_72'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_37',
		name: 'Step 37 Name',
		description: 'Step 37 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_73','param_74'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_38',
		name: 'Step 38 Name',
		description: 'Step 38 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_75','param_76'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_39',
		name: 'Step 39 Name',
		description: 'Step 39 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_77','param_78'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_40',
		name: 'Step 40 Name',
		description: 'Step 40 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_79','param_80'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_41',
		name: 'Step 41 Name',
		description: 'Step 41 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_81','param_82'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_42',
		name: 'Step 42 Name',
		description: 'Step 42 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_83','param_84'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_43',
		name: 'Step 43 Name',
		description: 'Step 43 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_85','param_86'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_44',
		name: 'Step 44 Name',
		description: 'Step 44 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_87','param_88'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},{
		id: 'step_45',
		name: 'Step 45 Name',
		description: 'Step 45 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_89','param_90'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_46',
		name: 'Step 46 Name',
		description: 'Step 46 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_91','param_92'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_47',
		name: 'Step 47 Name',
		description: 'Step 47 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_93','param_94'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_48',
		name: 'Step 48 Name',
		description: 'Step 48 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_95','param_96'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_49',
		name: 'Step 49 Name',
		description: 'Step 49 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_97','param_98'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_50',
		name: 'Step 50 Name',
		description: 'Step 50 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_99','param_100'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_51',
		name: 'Step 51 Name',
		description: 'Step 51 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_101','param_102'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_52',
		name: 'Step 52 Name',
		description: 'Step 52 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_103','param_104'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},{
		id: 'step_53',
		name: 'Step 53 Name',
		description: 'Step 53 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_105','param_106'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_54',
		name: 'Step 54 Name',
		description: 'Step 54 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_107','param_108'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_55',
		name: 'Step 55 Name',
		description: 'Step 55 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_109','param_110'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_56',
		name: 'Step 56 Name',
		description: 'Step 56 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_111','param_112'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_57',
		name: 'Step 57 Name',
		description: 'Step 57 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_113','param_114'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_58',
		name: 'Step 58 Name',
		description: 'Step 58 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_115','param_116'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_59',
		name: 'Step 59 Name',
		description: 'Step 59 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_117','param_118'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_60',
		name: 'Step 60 Name',
		description: 'Step 60 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_119','param_120'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_61',
		name: 'Step 61 Name',
		description: 'Step 61 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_121','param_122'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_62',
		name: 'Step 62 Name',
		description: 'Step 62 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_123','param_124'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_63',
		name: 'Step 63 Name',
		description: 'Step 63 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_125','param_126'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_64',
		name: 'Step 64 Name',
		description: 'Step 64 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_127','param_128'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_65',
		name: 'Step 65 Name',
		description: 'Step 65 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_129','param_130'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_66',
		name: 'Step 66 Name',
		description: 'Step 66 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_131','param_132'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_67',
		name: 'Step 67 Name',
		description: 'Step 67 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_133','param_134'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_68',
		name: 'Step 68 Name',
		description: 'Step 68 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_135','param_136'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_69',
		name: 'Step 69 Name',
		description: 'Step 69 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_137','param_138'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_70',
		name: 'Step 70 Name',
		description: 'Step 70 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_139','param_140'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_71',
		name: 'Step 71 Name',
		description: 'Step 71 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_141','param_142'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_72',
		name: 'Step 72 Name',
		description: 'Step 72 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_143','param_144'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_73',
		name: 'Step 73 Name',
		description: 'Step 73 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_145','param_146'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_74',
		name: 'Step 74 Name',
		description: 'Step 74 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_147','param_148'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_75',
		name: 'Step 75 Name',
		description: 'Step 75 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_149','param_150'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_76',
		name: 'Step 76 Name',
		description: 'Step 76 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_151','param_152'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_77',
		name: 'Step 77 Name',
		description: 'Step 77 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_153','param_154'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_78',
		name: 'Step 78 Name',
		description: 'Step 78 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_155','param_156'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_79',
		name: 'Step 79 Name',
		description: 'Step 79 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_157','param_158'],
		keyword: 'keyword_1',
		startTime: '',
		endTime: '',
	},
	{
		id: 'step_80',
		name: 'Step 80 Name',
		description: 'Step 80 Description',
		enabled: true,
		status: 'pass',
		type: 'step',
		client: 'chrome',
		imgURL: '',
		params: ['param_159','param_160'],
		keyword: 'keyword_2',
		startTime: '',
		endTime: '',
	},
]

let keywords = [
	{
		id: 'keyword_1',
		name: 'LaunchBrowser',
		description: 'Open webdriver and go to given url',
		author: 'thaihoang.nguyen@acomsolutions.com',
		type: 'keyword',
		imgURL: '',
		params: [
			{
				name: 'user_name',
				description: 'User Name \n enter',
				defaultValue: 'tindecken'
			},
			{
				name: 'password',
				description: 'Password \n enter',
				defaultValue: 'thisispassword'
			}
		],
	},
	{
		id: 'keyword_2',
		name: 'Login',
		description: 'Will input user name / password',
		author: 'thaihoang.nguyen@acomsolutions.com',
		type: 'keyword',
		imgURL: '',
		params: [
			{
				name: 'sUrl',
				description: 'User Name need to go',
				defaultValue: 'http://google.com'
			},
			{
				name: 'sExpectedTitle',
				description: 'Expected Title after go to page',
				defaultValue: 'Google - Google Chrome'
			}
		],
	},
]

let params = [
	{
		id: 'param_1',
		name: 'Param 1 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_2',
		name: 'Param 2 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_3',
		name: 'Param 3 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_4',
		name: 'Param 4 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_5',
		name: 'Param 5 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_6',
		name: 'Param 6 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_7',
		name: 'Param 7 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_8',
		name: 'Param 8 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_9',
		name: 'Param 9 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_10',
		name: 'Param 10 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_11',
		name: 'Param 11 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_12',
		name: 'Param 12 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_13',
		name: 'Param 13 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_14',
		name: 'Param 14 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_15',
		name: 'Param 15 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_16',
		name: 'Param 16 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_17',
		name: 'Param 17 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_18',
		name: 'Param 18 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_19',
		name: 'Param 19 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_20',
		name: 'Param 20 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_21',
		name: 'Param 21 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_22',
		name: 'Param 22 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_23',
		name: 'Param 23 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_24',
		name: 'Param 24 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_25',
		name: 'Param 25 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_26',
		name: 'Param 26 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_27',
		name: 'Param 27 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_28',
		name: 'Param 28 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_29',
		name: 'Param 29 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_30',
		name: 'Param 30 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_31',
		name: 'Param 31 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_32',
		name: 'Param 32 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_33',
		name: 'Param 33 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_34',
		name: 'Param 34 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_35',
		name: 'Param 35 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_36',
		name: 'Param 36 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_37',
		name: 'Param 37 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_38',
		name: 'Param 38 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_39',
		name: 'Param 39 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_40',
		name: 'Param 40 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_41',
		name: 'Param 41 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_42',
		name: 'Param 42 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_43',
		name: 'Param 43 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_44',
		name: 'Param 44 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_45',
		name: 'Param 45 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_46',
		name: 'Param 46 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_47',
		name: 'Param 47 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_48',
		name: 'Param 48 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_49',
		name: 'Param 49 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_50',
		name: 'Param 50 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_51',
		name: 'Param 51 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_52',
		name: 'Param 52 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_53',
		name: 'Param 53 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_54',
		name: 'Param 54 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_55',
		name: 'Param 55 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_56',
		name: 'Param 56 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_57',
		name: 'Param 57 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_58',
		name: 'Param 58 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_59',
		name: 'Param 59 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_60',
		name: 'Param 60 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_61',
		name: 'Param 61 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_62',
		name: 'Param 62 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_63',
		name: 'Param 63 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_64',
		name: 'Param 64 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_65',
		name: 'Param 65 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_66',
		name: 'Param 66 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_67',
		name: 'Param 67 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_68',
		name: 'Param 68 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_69',
		name: 'Param 69 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_70',
		name: 'Param 70 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_71',
		name: 'Param 71 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_72',
		name: 'Param 72 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_73',
		name: 'Param 73 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_74',
		name: 'Param 74 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_75',
		name: 'Param 75 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_76',
		name: 'Param 76 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_77',
		name: 'Param 77 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_78',
		name: 'Param 78 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_79',
		name: 'Param 79 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_80',
		name: 'Param 80 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_81',
		name: 'Param 81 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_82',
		name: 'Param 82 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_83',
		name: 'Param 83 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_84',
		name: 'Param 84 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_85',
		name: 'Param 85 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_86',
		name: 'Param 86 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_87',
		name: 'Param 87 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_88',
		name: 'Param 88 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_89',
		name: 'Param 89 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_90',
		name: 'Param 90 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_91',
		name: 'Param 91 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_92',
		name: 'Param 92 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_93',
		name: 'Param 93 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_94',
		name: 'Param 94 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_95',
		name: 'Param 95 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_96',
		name: 'Param 96 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_97',
		name: 'Param 97 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_98',
		name: 'Param 98 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_99',
		name: 'Param 99 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_100',
		name: 'Param 100 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_101',
		name: 'Param 101 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_102',
		name: 'Param 102 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_103',
		name: 'Param 103 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_104',
		name: 'Param 104 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_105',
		name: 'Param 105 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_106',
		name: 'Param 106 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_107',
		name: 'Param 107 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_108',
		name: 'Param 108 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_109',
		name: 'Param 109 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_110',
		name: 'Param 110 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_111',
		name: 'Param 111 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_112',
		name: 'Param 112 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_113',
		name: 'Param 113 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_114',
		name: 'Param 114 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_115',
		name: 'Param 115 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_116',
		name: 'Param 116 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_117',
		name: 'Param 117 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_118',
		name: 'Param 118 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_119',
		name: 'Param 119 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_120',
		name: 'Param 120 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_121',
		name: 'Param 121 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_122',
		name: 'Param 122 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_123',
		name: 'Param 123 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_124',
		name: 'Param 124 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_125',
		name: 'Param 125 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_126',
		name: 'Param 126 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_127',
		name: 'Param 127 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_128',
		name: 'Param 128 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_129',
		name: 'Param 129 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_130',
		name: 'Param 130 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_131',
		name: 'Param 131 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_132',
		name: 'Param 132 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_133',
		name: 'Param 133 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_134',
		name: 'Param 134 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_135',
		name: 'Param 135 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_136',
		name: 'Param 136 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_137',
		name: 'Param 137 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_138',
		name: 'Param 138 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_139',
		name: 'Param 139 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_140',
		name: 'Param 140 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_141',
		name: 'Param 141 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_142',
		name: 'Param 142 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_143',
		name: 'Param 143 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_144',
		name: 'Param 144 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_145',
		name: 'Param 145 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_146',
		name: 'Param 146 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_147',
		name: 'Param 147 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_148',
		name: 'Param 148 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_149',
		name: 'Param 149 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_150',
		name: 'Param 150 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_151',
		name: 'Param 151 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_152',
		name: 'Param 152 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_153',
		name: 'Param 153 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_154',
		name: 'Param 154 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_155',
		name: 'Param 155 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_156',
		name: 'Param 156 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_157',
		name: 'Param 157 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_158',
		name: 'Param 158 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_159',
		name: 'Param 159 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
	{
		id: 'param_160',
		name: 'Param 160 Name',
		description: 'parameter description',
		default: '',
		value: 'value',
		testBed: '',
	},
]

let clients = [
	{
		id: 'client_chrome',
		type: 'client',
		name: 'Chrome',
		description: 'Chrome client',
		ip: '',
		path: '',
	},
	{
		id: 'client_azurestorage',
		type: 'client',
		name: 'Azure Storage',
		description: 'Client of Azure Storage',
		ip: '',
		path: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
	}
]

export default {
	users,
	categories,
	testsuites,
	testgroups,
	testcases,
	keywords,
	params,
	clients,
	steps
}
