let users = [
	{
		name: 'Thai Hoang Nguyen',
		email: 'thaihoang.nguyen@acomsolutions.com',
		password: 'rivaldo',
		id: 'thaihoang.nguyen@acomsolutions.com',
		categories: ['category_bank_account'],
		testsuites: [],
		type: 'user'
	},
	{
		name: 'Thien Vo',
		email: 'thien.vo@acomsolutions.com',
		password: 'rivaldo',
		type: 'user',
		id: 'thien.vo@acomsolutions.com',
		testsuites: [],
		categories: ['category_payment']
	},
]

let categories = [
	{
		name: 'Bank Account',
		description: 'Bank Account Category',
		author: 'thaihoang.nguyen@acomsolutions.com',
		id: 'category_bank_account',
		type: 'category',
		testsuites: ['testsuite_pending', 'testsuite_approval'],
		status: 'pass',
		work_items: [15149, 15150]
	},
	{
		name: 'Payment',
		description: 'Payment Category',
		author: 'thien.vo@acomsolutions.com',
		id: 'category_payment',
		type: 'category',
		testsuites: ['testsuite_notification', 'testsuite_ach'],
		status: 'fail',
		work_items: [15151]
	}
]

let testsuites = [
	{
		name: 'Pending',
		description: 'testsuite Pending',
		author: 'thaihoang.nguyen@acomsolutions.com',
		id: 'testsuite_pending',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_pending', 'testgroup_primary_pending'],
		testcases: ['testcase_pending_1', 'testcase_pending_2'],
		category: 'category_payment', //không quan trọng phải có item này
		work_items: [15152, 15153]
	},
	{
		name: 'Approval',
		description: 'testsuite Aproval',
		author: 'thien.vo@acomsolutions.com',
		id: 'testsuite_approval',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_approval', 'testgroup_primary_approval'],
		testcases: ['testcase_approval_1', 'testcase_approval_2'],
		category: 'category_payment',
		work_items: [15154, 15155]
	},
	{
		name: 'Notification',
		description: 'testsuite Notification',
		author: 'thaihoang.nguyen@acomsolutions.com',
		id: 'testsuite_notification',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_notification', 'testgroup_primary_notification'],
		testcases: [],
		category: 'category_bank_account',
		work_items: [15156, 15157]
	},
	{
		name: 'ACH',
		description: 'testsuite ACH',
		author: 'thien.vo@acomsolutions.com',
		id: 'testsuite_ach',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_ach', 'testgroup_primary_ach'],
		testcases: [],
		category: 'category_bank_account',
		work_items: [15158, 15159]

	}
]

let testgroups = [
	{
		name: 'Group Preconfig Pending',
		description: 'testgroup Preconfig Pending',
		id: 'testgroup_preconfig_pending',
		testcases: ['testcase_preconfig_pending_1', 'testcase_preconfig_pending_2'],
		testsuite: 'testsuite_pending',
		work_items: [15160, 15161]
	},
	{
		id: 'testgroup_primary_pending',
		name: 'Group Primary Pending',
		description: 'testgroup Primary Pending',
		testcases: ['testcase_primary_pending_1', 'testcase_primary_pending_2'],
		testsuite: 'testsuite_pending',
		work_items: [15162, 15163]
	},
	{
		id: 'testgroup_preconfig_approval',
		name: 'Group Preconfig Approval',
		description: 'testgroup Preconfig Aproval',
		testcases: ['testcase_preconfig_approval_1', 'testcase_preconfig_approval_2'],
		testsuite: 'testsuite_approval',
		work_items: [15164, 15165]
	},
	{
		id: 'testgroup_primary_approval',
		name: 'Group Primary Approval',
		description: 'testgroup Primary Aproval',
		testcases: ['testcase_primary_approval_1', 'testcase_primary_approval_2'],
		testsuite: 'testsuite_approval',
		work_items: [15166, 15167]
	},
	{
		id: 'testgroup_preconfig_notification',
		name: 'Group Preconfig Notification',
		description: 'testgroup Preconfig Notification',
		testcases: ['testcase_preconfig_notification_1'],
		testsuite: 'testsuite_notification',
		work_items: [15168, 15169]
	},
	{
		id: 'testgroup_primary_notification',
		name: 'Group Primary Notification',
		description: 'testgroup Primary Notification',
		testcases: ['testcase_primary_notification_1'],
		testsuite: 'testsuite_notification',
		work_items: [15170, 15171]
	},
	{
		id: 'testgroup_preconfig_ach',
		name: 'Group Preconfig ACH',
		description: 'testgroup Preconfig ACH',
		testcases: ['testcase_preconfig_ach_1'],
		testsuite: 'testsuite_ach',
		work_items: [15172, 15173]
	},
	{
		id: 'testgroup_primary_ach',
		name: 'Group Primary ACH',
		description: 'testgroup Primary ACH',
		testcases: ['testcase_primary_ach_1'],
		testsuite: 'testsuite_ach',
		work_items: [15174, 15175]
	}
]

let testcases = [
	{
		id: 'testcase_pending_1',
		name: 'Testcase Pending 1',
		description: 'testcase Pending 1',
		type: 'testcase',
		keywords: ['keyword_1','keyword_2','keyword_3','keyword_4','keyword_5',],
		testsuite: 'testsuite_pending',
		work_items: [15176],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_pending_2',
		name: 'Testcase Pending 2',
		description: 'testcase Pending 2',
		type: 'testcase',
		keywords: ['keyword_6','keyword_7','keyword_8','keyword_9','keyword_10',],
		testsuite: 'testsuite_pending',
		work_items: [15177],
		enabled: true,
		primary: false,
		dependency: 'testcase_pending_1',
	},
	{
		id: 'testcase_approval_1',
		name: 'Testcase Aproval 1',
		description: 'testcase Aproval 1',
		type: 'testcase',
		keywords: ['keyword_11','keyword_12','keyword_13','keyword_14','keyword_15',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15178],
		enabled: true,
		primary: false,
		dependency: 'testcase_pending_1',
	},
	{
		id: 'testcase_approval_2',
		name: 'Testcase Aproval 2',
		description: 'testcase Aproval 2',
		type: 'testcase',
		keywords: ['keyword_16','keyword_17','keyword_18','keyword_19','keyword_20',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15179],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_pending_1',
		name: 'Testcase Preconfig Pending 1',
		description: 'testcase Preconfig Pending 1',
		type: 'testcase',
		keywords: ['keyword_21','keyword_22','keyword_23','keyword_24','keyword_25',],
		testgroup: 'testgroup_preconfig_pending',
		testsuite: '',
		work_items: [15180],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_pending_2',
		name: 'Testcase Preconfig Pending 2',
		description: 'testcase Preconfig Pending 2',
		type: 'testcase',
		keywords: ['keyword_26','keyword_27','keyword_28','keyword_29','keyword_30',],
		testgroup: 'testgroup_preconfig_pending',
		testsuite: '',
		work_items: [15181],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_pending_1',
		name: 'Testcase Primary Pending1',
		description: 'testcase Primary Pending 1',
		type: 'testcase',
		keywords: ['keyword_31','keyword_32','keyword_33','keyword_34','keyword_35',],
		testgroup: 'testgroup_primary_pending',
		testsuite: '',
		work_items: [15182],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_primary_pending_2',
		name: 'Testcase Primary Pending2',
		description: 'testcase Primary Pending 2',
		type: 'testcase',
		keywords: ['keyword_36','keyword_37','keyword_38','keyword_39','keyword_40',],
		testgroup: 'testgroup_primary_pending',
		testsuite: '',
		work_items: [15183],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_approval_1',
		name: 'Testcase Preconfig Approval 1',
		description: 'testcase Preconfig Aproval 1',
		type: 'testcase',
		keywords: ['keyword_41','keyword_42','keyword_43','keyword_44','keyword_45',],
		testgroup: 'testgroup_preconfig_approval',
		testsuite: '',
		work_items: [15184],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_approval_2',
		name: 'Testcase Preconfig Approval 2',
		description: 'testcase Preconfig Aproval 2',
		type: 'testcase',
		keywords: ['keyword_46','keyword_47','keyword_48','keyword_49','keyword_50',],
		testgroup: 'testgroup_preconfig_approval',
		testsuite: '',
		work_items: [15185],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_approval_1',
		name: 'Testcase Primary Approval 1',
		description: 'testcase Primary Aproval 1',
		type: 'testcase',
		keywords: ['keyword_51','keyword_52','keyword_53','keyword_54','keyword_55',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15186],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_approval_2',
		name: 'Testcase Primary Approval 2',
		description: 'testcase Primary Aproval 2',
		type: 'testcase',
		keywords: ['keyword_56','keyword_57','keyword_58','keyword_59','keyword_60',],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15187],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_notification_1',
		name: 'Testcase Preconfig Notification 1',
		description: 'testcase Preconfig Notification ',
		type: 'testcase',
		keywords: ['keyword_61','keyword_62','keyword_63','keyword_64','keyword_65',],
		testgroup: 'testgroup_preconfig_notification',
		testsuite: '',
		work_items: [15188],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_notification_1',
		name: 'Testcase Primary Notification 1',
		description: 'testcase Primary Notification 1',
		type: 'testcase',
		keywords: ['keyword_66','keyword_67','keyword_68','keyword_69','keyword_70',],
		testgroup: 'testgroup_preconfig_notification',
		testsuite: '',
		work_items: [15189],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_ach_1',
		name: 'Testcase Preconfig ACH1',
		description: 'testcase Preconfig ACH1',
		type: 'testcase',
		keywords: ['keyword_71','keyword_72','keyword_73','keyword_74','keyword_75',],
		testgroup: 'testgroup_preconfig_ach',
		testsuite: '',
		work_items: [15190],
		tickable: false,
		enabled: false,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_ach_1',
		name: 'Testcase Primary ACH 1',
		description: 'testcase Primary ACH ',
		type: 'testcase',
		keywords: ['keyword_76','keyword_77','keyword_78','keyword_79','keyword_80',],
		testgroup: 'testgroup_primary_ach',
		testsuite: '',
		work_items: [15191],
		enabled: true,
		primary: true,
		dependency: '',
	}
]

let keywords = [
	{
		id: 'keyword_1',
		name: 'Keywork 1 Name',
		description: 'Keywork 1 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_2',
		name: 'Keywork 2 Name',
		description: 'Keywork 2 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_3',
		name: 'Keywork 3 Name',
		description: 'Keywork 3 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_4',
		name: 'Keywork 4 Name',
		description: 'Keywork 4 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},{
		id: 'keyword_5',
		name: 'Keywork 5 Name',
		description: 'Keywork 5 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_6',
		name: 'Keywork 6 Name',
		description: 'Keywork 6 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_7',
		name: 'Keywork 7 Name',
		description: 'Keywork 7 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_8',
		name: 'Keywork 8 Name',
		description: 'Keywork 8 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_9',
		name: 'Keywork 9 Name',
		description: 'Keywork 9 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_10',
		name: 'Keywork 10 Name',
		description: 'Keywork 10 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_11',
		name: 'Keywork 11 Name',
		description: 'Keywork 11 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_12',
		name: 'Keywork 12 Name',
		description: 'Keywork 12 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_13',
		name: 'Keywork 13 Name',
		description: 'Keywork 13 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_14',
		name: 'Keywork 14 Name',
		description: 'Keywork 14 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_15',
		name: 'Keywork 15 Name',
		description: 'Keywork 15 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_16',
		name: 'Keywork 16 Name',
		description: 'Keywork 16 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_17',
		name: 'Keywork 17 Name',
		description: 'Keywork 17 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_18',
		name: 'Keywork 18 Name',
		description: 'Keywork 18 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_19',
		name: 'Keywork 19 Name',
		description: 'Keywork 19 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_20',
		name: 'Keywork 20 Name',
		description: 'Keywork 20 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_21',
		name: 'Keywork 21 Name',
		description: 'Keywork 21 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_22',
		name: 'Keywork 22 Name',
		description: 'Keywork 22 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_23',
		name: 'Keywork 23 Name',
		description: 'Keywork 23 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_24',
		name: 'Keywork 24 Name',
		description: 'Keywork 24 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_25',
		name: 'Keywork 25 Name',
		description: 'Keywork 25 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_26',
		name: 'Keywork 26 Name',
		description: 'Keywork 26 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_27',
		name: 'Keywork 27 Name',
		description: 'Keywork 27 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_28',
		name: 'Keywork 28 Name',
		description: 'Keywork 28 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_29',
		name: 'Keywork 29 Name',
		description: 'Keywork 29 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_30',
		name: 'Keywork 30 Name',
		description: 'Keywork 30 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_31',
		name: 'Keywork 31 Name',
		description: 'Keywork 31 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_32',
		name: 'Keywork 32 Name',
		description: 'Keywork 32 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_33',
		name: 'Keywork 33 Name',
		description: 'Keywork 33 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_34',
		name: 'Keywork 34 Name',
		description: 'Keywork 34 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_35',
		name: 'Keywork 35 Name',
		description: 'Keywork 35 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_36',
		name: 'Keywork 36 Name',
		description: 'Keywork 36 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_37',
		name: 'Keywork 37 Name',
		description: 'Keywork 37 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_38',
		name: 'Keywork 38 Name',
		description: 'Keywork 38 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_39',
		name: 'Keywork 39 Name',
		description: 'Keywork 39 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
	{
		id: 'keyword_40',
		name: 'Keywork 40 Name',
		description: 'Keywork 40 Description',
		author: 'thaihoang.nguyen@acomsolutions.com',
		enabled: true,
		status: 'pass',
		type: 'keywork',
		client: 'chrome',
		params: [],
	},
]

let params = [
	{

	}
]

export default {
	users,
	categories,
	testsuites,
	testgroups,
	testcases,
	keywords,
	params
}
